### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by NickHardeman** [mattfelsen/ofxOrbbecAstra#1]
Hi Matt,
Excited to get the Astra camera up and running.
Having a little trouble compiling this addon. I keep getting the error:
`dyld: Library not loaded: @rpath/libAstra.dylib
  Referenced from: /Users/NickHardeman/Documents/ProjectsDev/CMA/0090RC_OSX_VS/addons/ofxOrbbecAstra/example/bin/example.app/Contents/MacOS/example
  Reason: image not found`

I am on OSX 10.8 and XCode 5.1.1. Orbbec states that the SDK should run on this system.
I tried simulating the script code for libfmod in the Build Phases and copying the framework, but nothing worked.

Any ideas?

**Comment by mattfelsen** [comment]
Hey Nick. I've been reading up on dylibs, linker paths, etc a bit recently and realize I need to revise the instructions...

Where did you put the dylibs? Inside the Frameworks folder in the app bundle? It worked for me if I put the 3 dylibs + Plugins folder inside the bin folder (not bin/data), but only worked when running from Xcode, not from the finder. Let me know if that works? 

On a different note, @jmsaavedra mentioned you're in Miami? I'm down here for a few weeks visiting family - if so it'd be great to meet and grab a 🍻!

**Comment by NickHardeman** [comment]
Hey Matt,
Thanks for the tip. I moved the lib/osx folder contents to the bin folder The application is compiling now, but I don't see any images, etc. :(

I moved to Miami recently. It would be great to meet up. I will send an email shortly.

**Comment by mattfelsen** [comment]
Oh, have you installed libusb? It's not in the readme but is required as well I believe. You can `brew install libusb` it

**Comment by NickHardeman** [comment]
Yeah I have like 5 versions of lib usb 1.0. :) 
I am trying to link it against the lib usb I download and put in the bin folder.

**Comment by mattfelsen** [comment]
Do you have one at `/usr/local/lib/libusb-1.0.0.dylib` though? I think that liborbbec.dylib is hard-coded to  look for it in that location, separate from any settings specified in the Xcode project.

```
$ pwd
/Users/matt/Documents/Code/openFrameworks/github/addons/ofxOrbbecAstra/example/bin/Plugins/openni2/OpenNI2/Drivers

$ otool -L liborbbec.dylib 
liborbbec.dylib:
    liborbbec.dylib (compatibility version 0.0.0, current version 0.0.0)
    /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1153.18.0)
    /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
    /usr/local/lib/libusb-1.0.0.dylib (compatibility version 2.0.0, current version 2.0.0)
    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
```

Are you getting any weird warnings/errors in the console when you launch the app? Maybe something failing to load/initialize? If I move libusb out of /usr/local/lib I get this:

```
2015-12-28 22:20:37,625 WARN  [orbbec.ni.oni_adapter_plugin] Failed to initialize OpenNI:   LibraryHandler: Couldn't load library liborbbec.dylib
    DeviceDriver: library handle is invalid for file liborbbec.dylib
    Couldn't understand file 'liborbbec.dylib' as a device driver
    Found no valid drivers
```

Here's what my folder structure is like..

![screen shot 2015-12-28 at 10 22 10 pm](https://cloud.githubusercontent.com/assets/2334552/12029128/a43ba548-adb1-11e5-98ce-5510aa4a83df.png)

**Comment by NickHardeman** [comment]
Yeah I have a /usr/local/libusb-1.0.0.dylib. I tried moving it and it still compiled. I also have a libusb-1.0.0.1.0.dylib, among other similarly named. 
I tried moving a downloaded lib usb into the same folder as the liborbbec.dylib and then using the name tool to change its location ( as described in this post by wouter: https://3dclub.orbbec3d.com/t/cant-run-samples-on-os-x/98/7 ). 

This is what otool prints out:
`/usr/local/lib/libusb-1.0.0.dylib (compatibility version 2.0.0, current version 2.0.0)
    /usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
    /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
    /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 744.19.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 169.3.0)`

![screen shot 2015-12-28 at 10 41 09 pm](https://cloud.githubusercontent.com/assets/142694/12029256/5e78d492-adb4-11e5-9a60-eb1f2c7bb4bf.png)

When I run the app with the libusb-1.0.0 in usr/local/ I get the print out:
`libusb:info [darwin_async_io_callback] an async io operation has completed
libusb:debug [handle_events] poll() returned 1
libusb:info [op_handle_events] checking fd 9 with revents = 0
libusb:info [op_handle_events] checking fd 11 with revents = 1
libusb:info [darwin_handle_callback] handling control completion with kernel status 0
libusb:debug [ctrl_transfer_cb] actual_length=12
libusb:debug [libusb_get_next_timeout] no URBs, no timeout!
libusb:debug [handle_events] poll() 2 fds with timeout in 1ms
libusb:debug [handle_events] poll() returned 0
libusb:debug [libusb_get_next_timeout] all URBs have already been processed for timeouts
libusb:debug [handle_events] poll() 2 fds with timeout in 1ms
libusb:debug [libusb_get_next_timeout] all URBs have already been processed for timeouts
libusb:debug [libusb_handle_events_timeout] another thread is doing event handling
libusb:info [darwin_async_io_callback] an async io operation has completed
libusb:debug [handle_events] poll() returned 1`

But when I remove the libusb-1.0.0 it seems to start properly. At least I can get some dimensions coming in
`2015-12-28 22:51:41,761 INFO  [astra.streamset] connecting to (1,0) on device/sensor0
2015-12-28 22:51:41,761 INFO  [astra.plugins.Stream] adding connection
2015-12-28 22:51:41,761 INFO  [astra.plugin_service] linking connection to bin -- stream: 7b04bb0 type: 1 conn: 7b0d428 bin: 7b07310
2015-12-28 22:51:41,762 INFO  [orbbec.ni.depthstream] depth registration: enabled, successful: yes
2015-12-28 22:51:41,762 INFO  [astra.streamset] connecting to (2,0) on device/sensor0
2015-12-28 22:51:41,762 INFO  [astra.plugins.Stream] adding connection
2015-12-28 22:51:41,762 INFO  [astra.plugin_service] linking connection to bin -- stream: 1cb82b0 type: 2 conn: 1cc2eb8 bin: 7b027e0
2015-12-28 22:51:41,762 INFO  [orbbec.ni.devicestream] mode change requested: 640x480x3@30 pf:200
2015-12-28 22:51:41,762 INFO  [orbbec.ni.devicestream] stream mode changed
2015-12-28 22:51:41,762 INFO  [orbbec.ni.devicestream] turn on stream 2
2015-12-28 22:51:41,762 INFO  [orbbec.ni.devicestream] starting oni stream of type: 2
2015-12-28 22:51:41,770 INFO  [orbbec.ni.devicestream] started oni stream of type: 2
2015-12-28 22:51:41,770 INFO  [orbbec.ni.device_streamset] adding stream type 2 to active streams
2015-12-28 22:51:41,770 INFO  [orbbec.ni.devicestream] mode change requested: 640x480x2@30 pf:100
2015-12-28 22:51:41,770 INFO  [orbbec.ni.devicestream] stream mode changed
2015-12-28 22:51:41,770 INFO  [orbbec.ni.devicestream] turn on stream 1
2015-12-28 22:51:41,770 INFO  [astra.streamset] connecting to (7,0) on device/sensor0
2015-12-28 22:51:41,877 INFO  [PointProcessor] creating point stream
2015-12-28 22:51:41,877 INFO  [astra.plugins.Stream] creating a 7, 0
2015-12-28 22:51:41,877 INFO  [astra.plugin_service] created stream -- handle 0x101a26c10 type: 7
2015-12-28 22:51:41,882 INFO  [astra.plugin_service] creating bin -- handle: 1a341d0 stream: 1a26c10 type: 7 size: 3686456
2015-12-28 22:51:41,882 INFO  [astra.plugins.Stream] adding connection
2015-12-28 22:51:41,882 INFO  [astra.plugin_service] linking connection to bin -- stream: 1a26c10 type: 7 conn: 1a22f28 bin: 1a341d0
2015-12-28 22:51:41,882 INFO  [PointProcessor] created point stream
2015-12-28 22:51:48,544 INFO  [orbbec.ni.depthstream] depth registration: disabled, successful: yes
2015-12-28 22:51:49,326 INFO  [orbbec.ni.depthstream] depth registration: enabled, successful: yes`

**Comment by mattfelsen** [comment]
Yikes, what a headache...not really sure what to suggest as far as getting up & running in OF/with this addon. Maybe try downloading [the SDK](https://orbbec3d.com/develop/) and try getting the pre-built samples running, and/or building the samples from source (requires `brew install cmake sfml`) to make sure the hardware/sdk is working in general, and then try bringing that into an OF app?

Also, the nicely-formatted html docs were accidentally omitted from the osx sdk download ([mentioned here](https://3dclub.orbbec3d.com/t/trouble-integrating-into-openframeworks-app/105)), but you can get them in the windows download. Everything you need should actually be in the readme.txt with the osx sdk, but the html docs are nice & helpful for understanding & working with the astra sdk in general.

**Comment by NickHardeman** [comment]
Thank you for all of the help. 
I was trying to avoid re-installing homebrew/macports, but it looks like I might need to so that I can compile the examples shipped with the SDK.

**Comment by mattfelsen** [comment]
Can you try running this app and see if it works, or what the console output is if not? I did a similar thing to wouter's suggestion, though looking at his steps I realize he doesn't mention setting `@rpath` anywhere, so I wonder if that was a missing step.
- copied libusb into the bin folder
- used install_name_tool to change the name to `@rpath/libusb-1.0.0.dylib`
- set `@rpath` to `@executable_path/../../../` in Xcode

I left the deployment target at 10.8 (I'm on 10.11) so hopefully there's no deployment target/base sdk issues keeping this from running.

[bin.zip](https://github.com/mattfelsen/ofxOrbbecAstra/files/74103/bin.zip)

**Comment by NickHardeman** [comment]
I tried compiling the example from the latest git repo and I got this error message. 
`2015-12-30 10:29:55,051 WARN  [orbbec.ni.oni_adapter_plugin] Failed to initialize OpenNI:  LibraryHandler: Couldn't load library liborbbec.dylib
    DeviceDriver: library handle is invalid for file liborbbec.dylib
    Couldn't understand file 'liborbbec.dylib' as a device driver
    LibraryHandler: Couldn't load library libusb-1.0.0.dylib
    DeviceDriver: library handle is invalid for file libusb-1.0.0.dylib
    Couldn't understand file 'libusb-1.0.0.dylib' as a device driver
    Found no valid drivers`

I installed homebrew and made all of the appropriate updates. I even tried compiling the samples, but since I'm on OSX 10.8 and Xcode 5.1, not all of them compiled. 
I thought the `make_unique` declaration in this file `astra_cxx_make_unique` would account for it, but I guess not. I had to comment out the make_unique function in ofType to get the addon to compile. 

The depth stream and color stream examples did compile and I tried running them from the command line. The depth stream was passing events, but the color stream was not. I tried the addon again, but only starting the depth stream and it worked! There must be an issue with the color stream, even just trying to start it makes everything else fail on my machine.

**Comment by NickHardeman** [comment]
But I can access the Astra color image by using PhotoBooth, so it might be something with the SDK?

**Comment by mattfelsen** [comment]
How funky. Well that's some progress, at least! You should post something on the [orbbec forums](https://3dclub.orbbec3d.com). Pinging @JoshBlake anyway ☺️

**Comment by NickHardeman** [comment]
Yup, glad to see something coming in. :)
I've had a lot of trouble with libs and 10.8. There must be some major differences between 10.8 newer versions of OSX regarding core libs and frameworks.

posted to the forums: https://3dclub.orbbec3d.com/t/color-image-not-firing-on-frame-event/192

**Comment by mattfelsen** [comment]
👍🏼 That's interesting...curious to see what the orbbec team says about it.

Between this looking like an issue on the SDK side, and the updates I pushed earlier to fix the linking issues, I'm gonna close this issue. Feel free to add more comments or reopen. Cheers!

**Comment by mattfelsen** [comment]
Actually, I'll add one more comment :smile: Since so many of the depth camera wrappers (ofxKinect, ofxKinectForWindows2, this addon) all have different APIs/different method names for the same functionality (e.g. `getDepthPixels()` vs `getDepthSource()->getPixels()` vs `getRawDepth()`), I started working on an addon that attempts to hide all that and provide a common API, regardless of which device or addon you're using. You can switch between different cameras with minimal hassle/minmal code changes...It's kind of like the ofBaseVideoPlayer/ofVideoPlayer pattern.

You might have the same kind of trouble with the astra stuff, but it might be worth a look:
https://github.com/mattfelsen/ofxDepthCamera/tree/refactor I think the example project is already set up for the astra, you may just have to enable a #define in ofxDepthCamera.h

**Comment by JoshBlake** [comment]
I've replied to the thread on the Orbbec forum. Thanks for the heads up.
