### ISSUE TITLE
Black screen on example

### ISSUE THREAD

**Issue by stirem** [mattfelsen/ofxOrbbecAstra#5]
Hi!

When trying to run the example, the window only shows black, except for the text. I can't see any error messages in the console. The RGB camera works fine in Photo Booth. I have not managed to get the sample projects from Orbbec to work yet. Any suggestions?

Setup: Xcode 7.3, OSX 10.11.4, Orbbec Astra Pro

**Comment by stirem** [comment]
With version 0.5.0 I got the SimpleStreamViewer sample in Astra SDK working. The SimpleColorViewer shows black.

**Comment by mattfelsen** [comment]
Hi @stirem. This is a known issue with the SDK and the Astra Pro. You can take a look at issues #2 and #3 for some more info & workarounds. The Astra SDK was just updated yesterday but sadly did not address this issue. Feel free to reopen if you have more questions.

**Comment by stirem** [comment]
When I comment out the astra.initColorStream(), the depth stream is working. I also got the color stream working simultaneously by using a normal ofVideoGrabber.

**Comment by mattfelsen** [comment]
Sounds right 👍🏼

You can keep an eye on this thread to watch for any updates to this issue in the Astra SDK:
https://3dclub.orbbec3d.com/t/put-newer-openni-version-on-github/389
